---
#file: roles/webserver/tasks/main.yml

- name: Install Git
  yum: name={{item}} state="latest"
  sudo: yes
  with_items:
    - git

- name: Make DRE Folder
  command: mkdir -p "/home/ec2-user/dre"

- name: Clone DRE Repository
  git: repo="git://github.com/amida-tech/DRE.git" dest="/home/ec2-user/dre"

- name: Add Extended Fedora Repo Public Key
  command: rpm --import https://fedoraproject.org/static/0608B895.txt
  sudo: yes

- name: Enable Extended Fedora Repository
  command:  rpm -Uvh http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm --force
  sudo: yes

- name: Install node.js and npm
  yum: name={{item}} enablerepo="epel" state="latest"
  sudo: yes
  with_items:
    - nodejs
    - npm
