---
#file: roles/dbserver/tasks/main.yml

- name: Remove mongod user if present
  user: name=mongod state=absent remove=yes

- name: Create the mongod group
  group: name=mongod system=yes

- name: Create the mongod user
  user: name=mongod group=mongod comment="MongoD" append=yes
  sudo: yes

- name: Create the data directory
  file: path={{mongodb_datadir_prefix}} owner=mongod group=mongod state=directory
  sudo: yes

- name: Install 10gen yum repo
  copy:  src=10gen.repo.j2 dest=/etc/yum.repos.d/10gen.repo
  sudo: yes

- name: Install mongodb
  yum: name={{item}} enablerepo="10gen" state="installed"
  sudo: yes
  with_items:
    - mongodb-org
